name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # bloc: ^8.1.0
  get: ^4.1.4
  dots_indicator: ^4.0.1
  shared_preferences: ^2.0.11
  intl: ^0.20.2
  google_maps_flutter: ^2.1.2
  geocoding: ^3.0.0
  geolocator: ^10.1.0 
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0 

flutter_icons:
  android: true
  ios: true  
  image_path: "assets/food_deliver_icon.png"
  adaptive_icon_foreground: "assets/play_store_512.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
