// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhARwS0xzOycCC6XpznUSu27YBE4_9iDo',
    appId: '1:909699046116:web:d68189cae8a62a05282af1',
    messagingSenderId: '909699046116',
    projectId: 'foodapp-6d9cb',
    authDomain: 'foodapp-6d9cb.firebaseapp.com',
    storageBucket: 'foodapp-6d9cb.firebasestorage.app',
    measurementId: 'G-61E6WNPGLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8t1wV8jUbWdt5htxEKglvTGq9AHXnIo',
    appId: '1:909699046116:android:a3b4b1dd52ff45ea282af1',
    messagingSenderId: '909699046116',
    projectId: 'foodapp-6d9cb',
    storageBucket: 'foodapp-6d9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa4hAS4wAO5cOZriRXKRpIbb7cvWcnsvg',
    appId: '1:909699046116:ios:de5d9d9d70109ead282af1',
    messagingSenderId: '909699046116',
    projectId: 'foodapp-6d9cb',
    storageBucket: 'foodapp-6d9cb.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa4hAS4wAO5cOZriRXKRpIbb7cvWcnsvg',
    appId: '1:909699046116:ios:de5d9d9d70109ead282af1',
    messagingSenderId: '909699046116',
    projectId: 'foodapp-6d9cb',
    storageBucket: 'foodapp-6d9cb.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhARwS0xzOycCC6XpznUSu27YBE4_9iDo',
    appId: '1:909699046116:web:d034a8081278d1cb282af1',
    messagingSenderId: '909699046116',
    projectId: 'foodapp-6d9cb',
    authDomain: 'foodapp-6d9cb.firebaseapp.com',
    storageBucket: 'foodapp-6d9cb.firebasestorage.app',
    measurementId: 'G-DSNFVESCPZ',
  );
}
